name: CI/CD Pipeline for Core Tools

on:
  push:
    branches: [main, develp]
  pull_request:
    branches: [main, develp]

env:
  PYTHON_VERSION: "3.13"
  POETRY_VERSION: "1.8.0"

jobs:
  test:
    name: Lint, Test, and CLI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # 3️⃣ Install Poetry
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: ${{ env.POETRY_VERSION }}
          virtualenvs-create: true
          virtualenvs-in-project: false

      # 4️⃣ Install dependencies
      - name: Install dependencies
        run: poetry install --no-interaction --no-ansi

      # 5️⃣ Run CLI help (sanity check)
      - name: Run CLI help
        run: poetry run tools-cli --help

      # 6️⃣ Lint code
      - name: Lint code (black, isort, autoflake, autopep8)
        run: |
            tools-cli lint-fix

      # 7️⃣ Run tests
      - name: Run pytest
        run: poetry run pytest -v --tb=short

      # 8️⃣ Clean build artifacts and __pycache__
      - name: Clean project
        run: |
          find . -type d -name "__pycache__" -exec rm -rf {} +
          find . -type f -name "*.pyc" -exec rm -f {} +
          find . -type f -name "*.pyo" -exec rm -f {} +
          find . -type f -name "*.backup" -exec rm -f {} +

      # 9️⃣ Optional: Upload coverage to Codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
